# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ruby-fs-stack}
  s.version = "0.5.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jimmy Zimmerman"]
  s.date = %q{2010-10-29}
  s.description = %q{A library that enables you to read and update information with the new.familysearch.org API.}
  s.email = %q{jimmy.zimmerman@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "examples/familytree_example.rb",
     "examples/login_example.rb",
     "lib/ruby-fs-stack.rb",
     "lib/ruby-fs-stack/assets/entrust-ca.crt",
     "lib/ruby-fs-stack/enunciate/LICENSE",
     "lib/ruby-fs-stack/enunciate/README",
     "lib/ruby-fs-stack/enunciate/familytree.rb",
     "lib/ruby-fs-stack/enunciate/identity.rb",
     "lib/ruby-fs-stack/errors.rb",
     "lib/ruby-fs-stack/familytree.rb",
     "lib/ruby-fs-stack/familytree/characteristic.rb",
     "lib/ruby-fs-stack/familytree/communicator.rb",
     "lib/ruby-fs-stack/familytree/event.rb",
     "lib/ruby-fs-stack/familytree/exist.rb",
     "lib/ruby-fs-stack/familytree/gender.rb",
     "lib/ruby-fs-stack/familytree/match.rb",
     "lib/ruby-fs-stack/familytree/name.rb",
     "lib/ruby-fs-stack/familytree/note.rb",
     "lib/ruby-fs-stack/familytree/ordinance.rb",
     "lib/ruby-fs-stack/familytree/pedigree.rb",
     "lib/ruby-fs-stack/familytree/person.rb",
     "lib/ruby-fs-stack/familytree/relationship.rb",
     "lib/ruby-fs-stack/familytree/search.rb",
     "lib/ruby-fs-stack/fs_communicator.rb",
     "lib/ruby-fs-stack/fs_utils.rb",
     "lib/ruby-fs-stack/identity.rb",
     "lib/ruby-fs-stack/identity/communicator.rb",
     "lib/ruby-fs-stack/warning_suppressor.rb",
     "ruby-fs-stack.gemspec",
     "spec/fixtures/fakeweb_response.txt",
     "spec/ruby-fs-stack/familytree/communicator_spec.rb",
     "spec/ruby-fs-stack/familytree/json/combine_request.js",
     "spec/ruby-fs-stack/familytree/json/combine_response.js",
     "spec/ruby-fs-stack/familytree/json/fakeweb_contributor.txt",
     "spec/ruby-fs-stack/familytree/json/fakeweb_pedigree.txt",
     "spec/ruby-fs-stack/familytree/json/fakeweb_pedigree2.txt",
     "spec/ruby-fs-stack/familytree/json/fakeweb_pedigree3.txt",
     "spec/ruby-fs-stack/familytree/json/fakeweb_properties.txt",
     "spec/ruby-fs-stack/familytree/json/match_KW3B-NNM.js",
     "spec/ruby-fs-stack/familytree/json/note_create_response.js",
     "spec/ruby-fs-stack/familytree/json/person/KJ86-3VD_all.js",
     "spec/ruby-fs-stack/familytree/json/person/KJ86-3VD_parents_families.js",
     "spec/ruby-fs-stack/familytree/json/person/KJ86-3VD_version.js",
     "spec/ruby-fs-stack/familytree/json/person/fakeweb_10_batch.txt",
     "spec/ruby-fs-stack/familytree/json/person/fakeweb_6_batch.txt",
     "spec/ruby-fs-stack/familytree/json/person/multiple_version_read.js",
     "spec/ruby-fs-stack/familytree/json/person/post_response.js",
     "spec/ruby-fs-stack/familytree/json/person/relationship_not_found.js",
     "spec/ruby-fs-stack/familytree/json/person/relationship_read.js",
     "spec/ruby-fs-stack/familytree/json/person/relationship_update.js",
     "spec/ruby-fs-stack/familytree/json/person/spouse_read.js",
     "spec/ruby-fs-stack/familytree/json/search.js",
     "spec/ruby-fs-stack/familytree/match_spec.rb",
     "spec/ruby-fs-stack/familytree/note_spec.rb",
     "spec/ruby-fs-stack/familytree/pedigree_spec.rb",
     "spec/ruby-fs-stack/familytree/person_spec.rb",
     "spec/ruby-fs-stack/familytree/relationship_spec.rb",
     "spec/ruby-fs-stack/familytree/search_spec.rb",
     "spec/ruby-fs-stack/familytree/spec_helper.rb",
     "spec/ruby-fs-stack/fs_communicator_spec.rb",
     "spec/ruby-fs-stack/fs_utils_spec.rb",
     "spec/ruby-fs-stack/identity/communicator_spec.rb",
     "spec/ruby-fs-stack/identity/json/login.js",
     "spec/ruby-fs-stack_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/jimmyz/ruby-fs-stack}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.requirements = ["This gem requires a json gem (json, json_pure, or json-jruby)."]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Ruby wrapper for all FamilySearch APIs.}
  s.test_files = [
    "spec/ruby-fs-stack/familytree/communicator_spec.rb",
     "spec/ruby-fs-stack/familytree/match_spec.rb",
     "spec/ruby-fs-stack/familytree/note_spec.rb",
     "spec/ruby-fs-stack/familytree/pedigree_spec.rb",
     "spec/ruby-fs-stack/familytree/person_spec.rb",
     "spec/ruby-fs-stack/familytree/relationship_spec.rb",
     "spec/ruby-fs-stack/familytree/search_spec.rb",
     "spec/ruby-fs-stack/familytree/spec_helper.rb",
     "spec/ruby-fs-stack/fs_communicator_spec.rb",
     "spec/ruby-fs-stack/fs_utils_spec.rb",
     "spec/ruby-fs-stack/identity/communicator_spec.rb",
     "spec/ruby-fs-stack_spec.rb",
     "spec/spec_helper.rb",
     "examples/familytree_example.rb",
     "examples/login_example.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<fakeweb>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<fakeweb>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<fakeweb>, [">= 0"])
  end
end
